Increase paused central alert warning duration
stackrox/rhacs-observability-resources pull request #109
Opened 2023-06-26 11:07 UTC by SimonBaeumer

2023-06-26 11:10 UTC, SimonBaeumer commented on resources/prometheus/unit_tests/RHACSFleetshardSyncCentralReconcilePaused.yaml
>        - eval_time: 52h
Should this be increased to 32 days so it tests a silenced alert?

2023-06-26 11:24 UTC, stehessel commented on resources/prometheus/unit_tests/RHACSFleetshardSyncCentralReconcilePaused.yaml
> -      - eval_time: 30h
You need to add more values to the test series, otherwise there is no data at `eval_time`.

2023-06-26 11:31 UTC, vladbologa requested changes
This alert will never fire if we set `for: 30d`

Because the metric is provided by `fleetshard-sync`, it's not provided during ACSCS releases (usually every 14 days) and basically the interval will reset to 0 every 14 days (or every time `fleetshard-sync` restarts)

2023-07-04 11:04 UTC, stehessel commented
Hmm the `sum by (exported_instance)` will resolve the issue of fleetshard-sync's pod label changing, but I think the release can still reset the `for` timer if there is a period without metrics.

We could try to solve this by using something like `avg_over_time` for 30 days, but it would have quite bad query performance. I would actually propose to remove the alert all together and instead add this to query to a dashboard.

2023-07-04 11:27 UTC, SimonBaeumer commented
@stehessel Thank for helping me out! Indeed,  I agree it is better to have it as a dashboard in Grafana. I am closing this PR in favor of the dashboard.

2023-07-04 11:27 UTC, closed without merging

2023-07-04 11:32 UTC, stehessel commented
Alright, let's remove the alert then as well. FYI there is another open PR that I'd like to merge before promoting new observability changes to prod - https://github.com/stackrox/rhacs-observability-resources/pull/112.